import streamlit as st
from PIL import Image

from rqle_ai_langchain_util.clarity_genie_example.clarity_genie import ClarityGenie

COMPANY_LOGO = Image.open('img/rqle_ai_logo.jpg')
APPLICATION_LOGO = Image.open('img/claritygenie_logo.jpg')
APPLICATION_NAME = 'ClarityGenie'

# set up the high-level configuration of the page
st.set_page_config(page_title=APPLICATION_NAME, page_icon=APPLICATION_LOGO,
                   layout='wide', initial_sidebar_state='collapsed')
st.image(image=APPLICATION_LOGO, width=100)

# information about / help component of the application
st.sidebar.image(image=COMPANY_LOGO, width=100)
st.sidebar.header(body='About')
st.sidebar.markdown(body="""
 **ClarityGenie** was developed by **RQle AI** to enable Generative AI developers to refine their prompts. More specifically, 
 it attempts to address to improve clarity and contextual understanding of prompts.
""")

st.sidebar.header(body='RQle AI')
st.sidebar.markdown(body="""
 **RQle AI** believes in the transformative potential of Generative AI. More specifically, it focuses on showcasing 
 real-world applications of how Generative AI can empower individuals and organizations worldwide in addressing 
 their customers' "*job to be done*" problems and create value for them.
""")

st.sidebar.header(body='Resources')
st.sidebar.markdown(body="""
- [GitHub Repository](https://github.com/qhreul/my-langchain-util)
- [LinkedIn Profile](https://www.linkedin.com/in/quentinreul/)
""")

st.sidebar.header(body='Disclaimer')
st.sidebar.markdown(body="""
This application was partially generated by a large language model (Generative AI). While the AI assisted in the 
generation of ideas and content, the final solution and its implementation remain the responsibility of the human user. 
It is important to critically evaluate and revise the AI-generated content to ensure its accuracy, appropriateness, 
and ethical implications.
""")

# information about the footer of the application (including logo and years)